import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { SearchCepProvider } from "@/context/SearchContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Consulta de CEP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SearchCepProvider>
          {children}
        </SearchCepProvider>
      </body>
    </html>
  );
}
